backend:
  name: github
  repo: UI-liam90/portfolio
  branch: master

media_folder: static/assets
public_folder: assets
media_folder_relative: true

collections:
  - name: portfolio-site
    label: Portfolio Site
    folder: src/pages/portfolio-site
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "potfolioSiteTemplate"}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - { name: body, label: Body, widget: markdown }